name: PHP Execution

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  generate_feed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Refresh Token
      run: | 
        echo "::add-mask::${{ github.sha }}" >> $GITHUB_ENV
    - name: php
      run: |
        php info.php
