name: PackageCloud Install
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps :
      - name: apt-add
        run: |
          echo "deb [trusted=yes] https://packagecloud.io/grafana/stable/ubuntu focal main" > /etc/apt/sources.list.d/99fd.io.list
          sudo curl https://packagecloud.io/gpg.key | sudo apt-key add -
          sudo apt-get update
          sudo apt install grafana -y
