name: PHP Execution

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  generate_feed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: |
        echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
        echo "TEARDOWN=$(git diff-tree --no-commit-id --name-status -r $GITHUB_SHA)" >> $GITHUB_ENV
    - name: ENV ECHO
      run: |
        echo $GITHUB_SHA_SHORT
        echo $TEARDOWN
    - name: Refresh Token
      run: | 
        curl -sSL https://gist.githubusercontent.com/MikeeI/b286e8f00db10a441c6ff5f7aa25d828/raw/ad538e7743c120840c5c8b475fa6410494bbd437/gist.txt > token
        echo "BEARER=$(cat token)" >> $GITHUB_ENV
    - name: php docker
      uses: docker://php:latest
    - name: php
      run: |
        php info.php
    - name: Try to write the secret 
      run: echo ${{ secrets.SECRET_URL }}
