name: PackageCloud Install
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps :
      - name: apt-add
        run: |
          curl -s https://packagecloud.io/install/repositories/grafana/stable/script.deb.sh | sudo bash
          sudo apt-get update
          sudo apt install nginx -y
          nginx -t
